//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicationsApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int Id_Medication { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
        public Nullable<int> Id_Frim { get; set; }
        public Nullable<int> Id_Pharmacy { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
